[package]
name = "lief-sys"
version = "0.1.0"
edition = "2021"

[dependencies]
cxx = "1.0.128"

[build-dependencies]
cxx-build = "1.0.128"
miette = { version = "7.2.0", features = ["fancy"] }
cmake = "0.1.51"
